In [5]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
crescendo_data = pd.read_csv('/content/Machine Learning Model .csv')

In [7]:
crescendo_data.head()

index annual_tunover        country            product_name  \
0      0   20,00,00,000          Russia  Vacuum Toilet System    
1      1   20,00,00,000           Italy  Vacuum Toilet System    
2      2   20,00,00,000  Czech Republic  Vacuum Toilet System    
3      3   20,00,00,000         Germany  Vacuum Toilet System    
4      4   20,00,00,000  United Kingdom  Vacuum Toilet System    

  type_of_co_operation foreign_company_name  
0   Technology Venture              Taurus   
1   Technology Venture         Intersys Srl  
2   Technology Venture    TRATEC-CS s.r.o..  
3   Technology Venture       Trainvac Group  
4   Technology Venture   Birley Joinery Ltd

In [8]:
crescendo_data.shape

(216, 6)

In [9]:
selected_features = ['product_name','type_of_co_operation','annual_tunover']
print(selected_features)

['product_name', 'type_of_co_operation', 'annual_tunover']


In [10]:
combined_features = crescendo_data['product_name']+' '+crescendo_data['type_of_co_operation']+' '+crescendo_data['annual_tunover']

In [11]:
print(combined_features)

0      Vacuum Toilet System  Technology Venture 20,00...
1      Vacuum Toilet System  Technology Venture 20,00...
2      Vacuum Toilet System  Technology Venture 20,00...
3      Vacuum Toilet System  Technology Venture 20,00...
4      Vacuum Toilet System  Technology Venture 20,00...
                             ...                        
211                     Casting OutSourcing 80,00,00,000
212                     Casting OutSourcing 80,00,00,000
213                     Casting OutSourcing 80,00,00,000
214                     Casting OutSourcing 80,00,00,000
215                     Casting OutSourcing 80,00,00,000
Length: 216, dtype: object


In [12]:
vectorizer = TfidfVectorizer()

In [13]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [14]:
print(feature_vectors)

  (0, 1)	0.13807763065919307
  (0, 0)	0.27615526131838614
  (0, 2)	0.23188991855704888
  (0, 20)	0.3407582427519489
  (0, 17)	0.3407582427519489
  (0, 16)	0.4541172921990273
  (0, 18)	0.4541172921990273
  (0, 19)	0.4541172921990273
  (1, 1)	0.13807763065919307
  (1, 0)	0.27615526131838614
  (1, 2)	0.23188991855704888
  (1, 20)	0.3407582427519489
  (1, 17)	0.3407582427519489
  (1, 16)	0.4541172921990273
  (1, 18)	0.4541172921990273
  (1, 19)	0.4541172921990273
  (2, 1)	0.13807763065919307
  (2, 0)	0.27615526131838614
  (2, 2)	0.23188991855704888
  (2, 20)	0.3407582427519489
  (2, 17)	0.3407582427519489
  (2, 16)	0.4541172921990273
  (2, 18)	0.4541172921990273
  (2, 19)	0.4541172921990273
  (3, 1)	0.13807763065919307
  :	:
  (211, 5)	0.7292060768468791
  (211, 13)	0.26245236592584875
  (211, 7)	0.4254820802742275
  (211, 1)	0.20896997510409174
  (211, 0)	0.4179399502081835
  (212, 5)	0.7292060768468791
  (212, 13)	0.26245236592584875
  (212, 7)	0.4254820802742275
  (212, 1)	0.20896997510

In [15]:
similarity = cosine_similarity(feature_vectors)

In [16]:
print(similarity)

[[1.        1.        1.        ... 0.1442704 0.1442704 0.1442704]
 [1.        1.        1.        ... 0.1442704 0.1442704 0.1442704]
 [1.        1.        1.        ... 0.1442704 0.1442704 0.1442704]
 ...
 [0.1442704 0.1442704 0.1442704 ... 1.        1.        1.       ]
 [0.1442704 0.1442704 0.1442704 ... 1.        1.        1.       ]
 [0.1442704 0.1442704 0.1442704 ... 1.        1.        1.       ]]


In [17]:
print(similarity.shape)

(216, 216)


In [67]:
client_name = input(' Enter your favourite client name : ')

 Enter your favourite client name : ZF Group


In [68]:
list_of_all_clients = crescendo_data['foreign_company_name'].tolist()
print(list_of_all_clients)

['Taurus ', '  Intersys Srl', 'TRATEC-CS s.r.o..', 'Trainvac Group', 'Birley Joinery Ltd', 'ALNAL RAILWAY SYSTEMS', 'Festo', 'ZF Group', 'AVK Group', 'Siemens', 'Mitsubhisi Fuso Trucks ', 'SINDO KOREA', 'JTEKT France  ', 'Monmet Canada', 'CAPI GROUP ', 'Maruei Industries', 'Chikuma Japan', 'Sidem Romania ', 'Begas Motor Spain', 'Begas Motor Spain', 'STREPARAVA ITALY ', 'Motovario Italy', 'Sodecia ', 'Sidem Romania ', 'Newbay Foundry', 'Pobjeda', 'Fonder shell', 'VALEO', 'KNORR B', 'CAPI GROUP ', 'Cummins ', 'TNG ', 'BONFIGLIOLI', 'VINFAST ', 'SONALO HORIZONTE', 'JG AUTOMOTIVE', 'SOLENO', 'AMUFER', 'STREPARAVA ITALY ', 'JTEKT France  ', 'Cemmer Turkey ', 'Sidem Romania ', 'Mitsubhisi Fuso Trucks ', 'Teshika Co., Ltd.', 'AGCO', 'AGCO', 'AGCO', 'SINDO KOREA', 'Monmet Canada', 'Mitsubhisi Fuso Trucks ', 'JTEKT France  ', 'JTEKT France  ', 'Cemmer Turkey ', 'CAPI GROUP ITALY', 'Nabtech Engineering Ireland', 'Nabtech Engineering Ireland', 'Begas Motor Spain', 'JTEKT France  ', 'AGCO', 'DANA 

In [69]:
find_close_match = difflib.get_close_matches(client_name, list_of_all_clients)
print(find_close_match)

['ZF Group', 'AVK Group', 'TAURUS Group']


In [70]:
close_match = find_close_match[0]
print(close_match)

ZF Group


In [71]:
index_of_the_client = crescendo_data[crescendo_data.foreign_company_name == close_match]['index'].values[0]
print(index_of_the_client)

7


In [72]:
similarity_score = list(enumerate(similarity[index_of_the_client]))
print(similarity_score)

[(0, 0.1596465540346893), (1, 0.1596465540346893), (2, 0.1596465540346893), (3, 0.1596465540346893), (4, 0.1596465540346893), (5, 0.1596465540346893), (6, 1.0000000000000002), (7, 1.0000000000000002), (8, 1.0000000000000002), (9, 1.0000000000000002), (10, 0.3244557838964318), (11, 0.3244557838964318), (12, 0.3244557838964318), (13, 0.3244557838964318), (14, 0.3244557838964318), (15, 0.3244557838964318), (16, 0.3244557838964318), (17, 0.3244557838964318), (18, 0.3244557838964318), (19, 0.3244557838964318), (20, 0.3244557838964318), (21, 0.3244557838964318), (22, 0.3244557838964318), (23, 0.3244557838964318), (24, 1.0000000000000002), (25, 1.0000000000000002), (26, 1.0000000000000002), (27, 1.0000000000000002), (28, 1.0000000000000002), (29, 1.0000000000000002), (30, 1.0000000000000002), (31, 1.0000000000000002), (32, 1.0000000000000002), (33, 1.0000000000000002), (34, 1.0000000000000002), (35, 1.0000000000000002), (36, 1.0000000000000002), (37, 1.0000000000000002), (38, 0.32445578389643

In [73]:
len(similarity_score)

216

In [74]:
sorted_similar_clients = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_clients)

[(6, 1.0000000000000002), (7, 1.0000000000000002), (8, 1.0000000000000002), (9, 1.0000000000000002), (24, 1.0000000000000002), (25, 1.0000000000000002), (26, 1.0000000000000002), (27, 1.0000000000000002), (28, 1.0000000000000002), (29, 1.0000000000000002), (30, 1.0000000000000002), (31, 1.0000000000000002), (32, 1.0000000000000002), (33, 1.0000000000000002), (34, 1.0000000000000002), (35, 1.0000000000000002), (36, 1.0000000000000002), (37, 1.0000000000000002), (58, 1.0000000000000002), (63, 1.0000000000000002), (64, 1.0000000000000002), (66, 1.0000000000000002), (71, 1.0000000000000002), (72, 1.0000000000000002), (73, 1.0000000000000002), (74, 1.0000000000000002), (79, 1.0000000000000002), (80, 1.0000000000000002), (90, 1.0000000000000002), (96, 1.0000000000000002), (110, 1.0000000000000002), (111, 1.0000000000000002), (112, 1.0000000000000002), (125, 1.0000000000000002), (137, 0.548073990342969), (138, 0.548073990342969), (139, 0.548073990342969), (144, 0.548073990342969), (172, 0.548

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_clients:
  index = movie[0]
  title_from_index = crescendo_data[crescendo_data.index==index]['foreign_company_name'].values[0]
  co_operaion_from_index = crescendo_data[crescendo_data.index==index]['type_of_co_operation'].values[0]
  product_name_from_index = crescendo_data[crescendo_data.index==index]['product_name'].values[0]
  annual_turnover_from_index = crescendo_data[crescendo_data.index==index]['annual_tunover'].values[0]
  if (i<30):
    print(i, 'Company Name :-',title_from_index,':\n Type of Co-operation :-',co_operaion_from_index,'\n Type of Product they are Intrested to buy:-',product_name_from_index,'\n Annual turnover of Buyer :-',annual_turnover_from_index)
    i+=1

In [108]:
def recomend_suitable_clients(client_name):
  find_close_match = difflib.get_close_matches(client_name, list_of_all_clients)
  close_match = find_close_match[0]
  index_of_the_client = crescendo_data[crescendo_data.foreign_company_name == close_match]['index'].values[0]
  similarity_score = list(enumerate(similarity[index_of_the_client]))
  sorted_similar_clients = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
  print('Movies suggested for you : \n')
  i = 1
  for movie in sorted_similar_clients:
    index = movie[0]
    title_from_index = crescendo_data[crescendo_data.index==index]['foreign_company_name'].values[0]
    co_operaion_from_index = crescendo_data[crescendo_data.index==index]['type_of_co_operation'].values[0]
    product_name_from_index = crescendo_data[crescendo_data.index==index]['product_name'].values[0]
    annual_turnover_from_index = crescendo_data[crescendo_data.index==index]['annual_tunover'].values[0]
    if (i<4):
      print(i, 'Company Name :-',title_from_index,':\n Type of Co-operation :-',co_operaion_from_index,'\n Type of Product they are Intrested to buy:-',product_name_from_index,'\n Annual turnover of Buyer :-',annual_turnover_from_index)
      i+=1
recomend_suitable_clients(input())

Hitachi Rail
Movies suggested for you : 

1 Company Name :- BondioliPavesi :
 Type of Co-operation :- OutSourcing 
 Type of Product they are Intrested to buy:- Casting 
 Annual turnover of Buyer :- 80,00,00,000
2 Company Name :- Dodge Industrial :
 Type of Co-operation :- OutSourcing 
 Type of Product they are Intrested to buy:- Casting 
 Annual turnover of Buyer :- 80,00,00,000
3 Company Name :- DB Santaslo :
 Type of Co-operation :- OutSourcing 
 Type of Product they are Intrested to buy:- Casting 
 Annual turnover of Buyer :- 80,00,00,000


In [78]:
import pickle

In [109]:
pickle.dump(crescendo_data,open("recomend_suitable_clients.pkl","wb"))
pickle.dump(similarity,open("similarity.pkl","wb"))